### ISSUE TITLE
Don't destructure req.body

### ISSUE THREAD

**Issue by baldarian** [codeep/chatter-backend#7]
https://github.com/codeep/chatter-backend/blob/cd2ea4ff7d4c5a0a0889f0424cc1cae8413cb724/routes/auth.js#L13

Why did you destructure it ? You could write instead like this.

`models.User.create(req.body);`

**Comment by Andran77** [comment]
before creation i have to change email and password
    email = email.toLowerCase();
    password = bcrypt.hashSync(String(password), 8);
